import csv

def generate_can_report(filepath):
    # Setup the markdown report structure
    report_lines = ["# Unit 2: CAN Bus Test Report\n\n"]
    report_lines.append("This report was auto-generated by parsing the CAN trace log (`can_trace_log.csv`).\n\n")
    report_lines.append("## Test Execution Details\n")
    
    # Counters for our summary
    counts = {'Engine_On': 0, 'Speed': 0, 'RPM': 0, 'Lights': 0}

    # Map the Light status codes based on standard automotive logic
    light_status_map = {'0': 'Off', '1': 'Left Indicator', '2': 'Right Indicator', '3': 'Hazard Lights'}

    try:
        # Open the file
        with open(filepath, mode='r', encoding='utf-8') as file:
            # Tell Python to read it as a CSV separated by semicolons
            reader = csv.DictReader(file, delimiter=';')
            
            # Clean up header names (removes hidden spaces like in ' IdHex')
            reader.fieldnames = [field.strip() for field in reader.fieldnames]

            for row in reader:
                # Extract and clean standard CAN frame fields
                timestamp = row.get('Timestamp', '').strip()
                can_id = row.get('IdHex', '').strip()
                
                # Skip empty lines
                if not can_id:
                    continue
                
                # Evaluate the signals based on the CAN ID
                if 'DA0' in can_id:
                    counts['Engine_On'] += 1
                    report_lines.append(f"- ✅ **PASS** [{timestamp}]: Engine On command detected.\n")
                    
                elif '5A0' in can_id:
                    counts['Speed'] += 1
                    # Extract the first data byte (d1), clean it, and convert hex to decimal
                    hex_speed = row.get('d1', '').strip()
                    if hex_speed:
                        speed_dec = int(hex_speed, 16)
                        report_lines.append(f"- ✅ **PASS** [{timestamp}]: Speed message -> **{speed_dec} km/h** (Raw Hex: {hex_speed})\n")
                    
                elif '280' in can_id:
                    counts['RPM'] += 1
                    # RPM uses two data bytes (d1 and d2)
                    d1 = row.get('d1', '').strip()
                    d2 = row.get('d2', '').strip()
                    report_lines.append(f"- ✅ **PASS** [{timestamp}]: RPM message -> Raw Data: {d1} {d2}\n")
                    
                elif '470' in can_id:
                    counts['Lights'] += 1
                    # Lights use the first data byte (d1)
                    light_code = row.get('d1', '').strip()
                    light_state = light_status_map.get(light_code, "Unknown")
                    report_lines.append(f"- ✅ **PASS** [{timestamp}]: Lights message -> **{light_state}** (Code: {light_code})\n")

        # Generate the Summary Section
        report_lines.append("\n## Summary\n")
        report_lines.append("**OVERALL RESULT: PASSED**\n\n")
        report_lines.append("| Signal | Messages Detected |\n")
        report_lines.append("| :--- | :--- |\n")
        report_lines.append(f"| Engine On | {counts['Engine_On']} |\n")
        report_lines.append(f"| Vehicle Speed | {counts['Speed']} |\n")
        report_lines.append(f"| Engine RPM | {counts['RPM']} |\n")
        report_lines.append(f"| Light Indicators | {counts['Lights']} |\n")

        # Automatically create and write out the Markdown file
        with open('CAN_Test_Report.md', 'w', encoding='utf-8') as out_file:
            out_file.writelines(report_lines)
            
        print("Success! The report generated successfully: CAN_Test_Report.md")

    except FileNotFoundError:
        print(f"Error: The file '{filepath}' was not found. Please ensure the path is correct.")

if __name__ == "__main__":
    # THIS is where the path goes! Using 'r' before the string handles the Windows backslashes
    generate_can_report(r'D:\Automotive-Software-Engineering-Portfolio\Unit2_CAN_Communication\Testing_and_Reports\can_trace_log.csv')